path_classifiers:
  library:
    - libocispec

extraction:
  cpp:
    prepare:
        packages:
             - libctemplate-dev
             - libjsoncpp-dev
             - libjsoncpp1
             - libdbus-1-dev
             - libnl-3-dev
             - libnl-route-3-dev
             - libsystemd-dev
             - libyajl-dev
             - libcap-dev
    configure:
      command:
        # make sure we build all optional plugins for max coverage. Newly developed plugins should be added to this list
        - cmake -DCMAKE_BUILD_TYPE=Debug -DRDK_PLATFORM=DEV_VM -DCMAKE_INSTALL_PREFIX:PATH=/usr -DLEGACY_COMPONENTS=ON -DPLUGIN_TESTPLUGIN=ON -DPLUGIN_GPU=ON -DPLUGIN_LOCALTIME=ON -DPLUGIN_RTSCHEDULING=ON -DPLUGIN_HTTPPROXY=ON -DPLUGIN_APPSERVICES=ON -DPLUGIN_IONMEMORY=ON -DPLUGIN_DEVICEMAPPER=ON